export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

export const CHECKOUT_PRODUCTS = "CHECKOUT_PRODUCTS";
export const CHECKOUT_PRODUCTS_ADD = "CHECKOUT_PRODUCTS_ADD";
export const CHECKOUT_PRODUCTS_REMOVE = "CHECKOUT_PRODUCTS_REMOVE";

export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
